// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCImUwHBDIMYh3jEV8GyOY99gnXkz8g9Kw',
    appId: '1:125630112049:web:d945b609165399da619010',
    messagingSenderId: '125630112049',
    projectId: 'gstock-a4784',
    authDomain: 'gstock-a4784.firebaseapp.com',
    storageBucket: 'gstock-a4784.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvov5kvIjDZf5jE3GRRim_Fs_TZ8qjoM0',
    appId: '1:125630112049:android:3b54e653440b0a5a619010',
    messagingSenderId: '125630112049',
    projectId: 'gstock-a4784',
    storageBucket: 'gstock-a4784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDakAwpu-g6on4jkcjbq_d4L4eFhj2dJHg',
    appId: '1:125630112049:ios:38fc8cb7fb2f9575619010',
    messagingSenderId: '125630112049',
    projectId: 'gstock-a4784',
    storageBucket: 'gstock-a4784.appspot.com',
    iosBundleId: 'com.example.gstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDakAwpu-g6on4jkcjbq_d4L4eFhj2dJHg',
    appId: '1:125630112049:ios:e769074a5b8a4ba6619010',
    messagingSenderId: '125630112049',
    projectId: 'gstock-a4784',
    storageBucket: 'gstock-a4784.appspot.com',
    iosBundleId: 'com.example.gstock.RunnerTests',
  );
}
